name: infinit_stocks_test_task
description: "Test assesstment for Infinit company"

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ^3.5.1

dependencies:
  auto_route: ^9.3.0
  core:
    path: packages/core
  domain:
    path: packages/domain
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  intl: ^0.20.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
