name: infinit_stocks_test_task
description: "Test assesstment for Infinit company"

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.1

dependencies:
  core:
    path: packages/core
  domain:
    path: packages/domain
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.3.0
  freezed_annotation: ^2.4.4
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
