name: core
description: Core package with core things, like DI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  data:
    path: ../data
  dio: ^5.7.0
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
