name: Analyze and Format

on:
  push:
    branches: [ main, feature/* ]

jobs:
  analyze_and_format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:3.24.3

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache Pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            /opt/flutter/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze